### ISSUE TITLE
inconsistent design of measure instruction

### ISSUE THREAD

**Issue by GiggleLiu** [QuantumBFS/YaoIR.jl#12]
```julia
            ck = @measure (i, j, k) repeat(3, H)
```
Maybe
```julia
            ck = @measure (i, j, k) => repeat(3, H)
```
is better?

**Comment by Roger-luo** [comment]
Measurement operator is separated from normal circuits in semantic (thus it can be other things than a `Circuit` object, e.g an AbstractBlock), since measurement operator is not the same as a quantum circuit in practice, where the gate location semantic (aka `<location> => <circuit>`) enforce it has to be a `Circuit` so things like location mapping etc. would happen

**Comment by GiggleLiu** [comment]
ok. Not fully convinced, but sounds like not a big issue.
Close?

**Comment by Roger-luo** [comment]
note `repeat(3, H)` is currently not a legal quantum circuit statement in YaoIR,  If we want `@measure (i, j, k) => repeat(3, H)` this means the compiler will infer whatever inside `@measure` statement to be a pure circuit to make sure it is unitary, and we will lose all the support for Hamiltonians from YaoBlocks, to summarize:

1. `@measure` statement requires an operator, which should be strictly a unitary, which will be guaranteed and supported by runtime check and YaoBlocks
2. gate location statement requires a strict quantum program constraint (which can be a hybrid program) that the compiler will guarantee.

I'm closing this since it's a feature.
